### ISSUE TITLE
example.py does not run

### ISSUE THREAD

**Issue by delineaKrehl** [DelineaXPM/python-tss-sdk#21]
**Description of the issue**

After initializing the proper environment variables, running example.py results in this error message
`Exception has occurred: TypeError
SecretServer.__init__() got an unexpected keyword argument 'username'`

**Expected behavior**

The example find a secret

**Actual behavior**

Error due to the example being out of sync with changes made to the server module

**Your environment**

Windows 11, VS Code

**Steps to reproduce**

1. Create the environment variables as referenced in example.py
2. Run example.py

**Comment by tylerezimmerman** [comment]
Running this on the current version and unable to reproduce

![image](https://github.com/DelineaXPM/python-tss-sdk/assets/100804646/cb6f9a71-90ba-4715-87f6-a8a0d6d0a0c8)
