### ISSUE TITLE
Provide Access to Attached Files

### ISSUE THREAD

**Issue by jifox** [DelineaXPM/python-tss-sdk#5]
## Feature / Enhancement proposed

Extend the API to read attached files.

**Usecase:**
To automate the setup of web/app servers it is necessary to access the private-key for the https service.

## Workarounds

None

## Has the feature been requested before?

[Here](https://github.com/thycotic/python-tss-sdk/issues/42)

## If the feature request is approved, would you be willing to submit a PR?

_(Help can be provided if you need assistance submitting a PR)_

[] Yes [x] No

**Comment by EndlessTrax** [comment]
Hi @jifox. Nice to see you again. 

`get_secret()` should return file attachments by default: 

```def get_secret(self, id, fetch_file_attachments=True, query_params=None)```

Is this not working for you? Do you have an example output you can share?

**Comment by tylerezimmerman** [comment]
@jifox Do you have any update on the above comment?

**Comment by jifox** [comment]
Hi it is working as expected now
